### PR TITLE
Content Restructure

### PR DESCRIPTION
**Pull request by mikeyhougland**
Reorganized navigation and added/edited content

### CODE REVIEW

**Comment by araiford** [comment]
Noticing that the tertiary buttons have some color problems and also have a border.  I think they're supposed to be borderless, no?

image

**Comment by mikeyhougland** [comment]
Tommy reviewed the page and said the colors/states are correct. There is a border on the default states for secondary and tertiary that matches the background color to prevent the button from shifting on hover, etc. We could eliminate the border and add padding to prevent the shift, however I was trying to stick to multiples of 4 as much as possible.

**Comment by araiford** [comment]
@mikeyhougland @tommy-shook -- I'm a little confused.  Mikey mentioned the border on tertiary buttons matches the background color.  Is the intent that the border is not visible for tertiary buttons?

**Comment by mikeyhougland** [comment]
@araiford @tommy-shook That is correct. The only visible border is on the secondary and tertiary button default states.

**Comment by araiford** [comment]
ok, thanks @mikeyhougland -- :shipit:

**Pull request merged**
