### PR TITLE
feat(logos): add CDN logos to iconography page

### PR DESCRIPTION
**Pull request by technabors**
This PR adds a new `<section>` for logos on the iconography page. Additionally a new class was generated to adjust the background color of the `<figure>` element for the light logo to display. #333333 was used as the bg-color, however this can be adjusted as needed.

I also wonder if we should link to the following page, "https://blog.rackspace.com/newsroom/logos". I used the email provided on the that page, however did not link to the blog article directly.

@CITguy @araiford Thoughts? ^

Edit: Screenshot updated
image

### CODE REVIEW

**Comment by CITguy** [comment]
So, it _seems_ alright to me, but we should double check with legal. Mainly because:

1. I'm not 100% sure if the public relations team is the appropriate contact for inquiries.
2. I'm not sure what verbiage is needed to document the legal usage of the images.
3. I'm not sure if we're missing something that's needed.

**Comment by CITguy** [comment]
With a little digging, I found https://www.rackspace.com/information/legal which has a link to https://www.rackspace.com/information/legal/copyrights_trademarks, which has a lot of useful information for _public consumption_. However, I'm not sure how formal we need to be given that the documentation _should_ be just for Racker use. I'll submit an inquiry with legal to see what else we need to do.

**Comment by CITguy** [comment]
Also, I have a feeling that we need to change the Fanatiguy image, because it's been modified.

**Comment by technabors** [comment]
@CITguy I like including the copyrights_trademarks link in this section as well.

**Comment by technabors** [comment]
@CITguy Take a look at the rackspace gray logo on the CDN, the text has been distorted. Any chance we could get an unmodified version replacement at the same link?

http://c1ee333499ed5f44e56a-fa12562cfe810d69bedcc36a0ac289ef.r55.cf1.rackcdn.com/img/rs-logo.svg

**Comment by CITguy** [comment]
@technabors: that's literally the same SVG being used on rackspace.com

**Comment by technabors** [comment]
@CITguy Ok no arguments from me then, just looked strange.

**Pull request merged**
