### PR TITLE
Code frame

### PR DESCRIPTION
**Pull request by nimbinatus**
Working on adding an iframe for code snippets

### CODE REVIEW

**Comment by nimbinatus** [comment]
@araiford here's the start of the code iframe. I'm still trying to get it to dynamically scale, but it should at least work for the demo tomorrow if you want to use it.

**Comment by nimbinatus** [comment]
@araiford, this one's ready for you to poke at :)

**Comment by technabors** [comment]
Howdy, so I reviewed the functionality and there are a few things I noted. I know this is a temporary work around for the time being so take these issues with a grain of salt.

1. Breadcrumbs: The family level component is not displaying once a Code & Examples page is displayed.
image

2. Navigation: Wayfinding or selected state is not being shown in the navigation when on a Code & Examples page. In the following example, Content Areas is in selected state when on the design guidelines page and not in selected state on Code and Examples page
image

3. The Meta data column is pushing into the screen between the following view sizes 968px - 1314px. Below these values the column displays above the content. Above these values the content is pushed off the screen and not displayed. Not sure if this is a huge issue but some speculation on my part says we could remove if it by finding the div with class `hxOrder-md-2` and deleting the node.
image

**Comment by nimbinatus** [comment]
Good points. I'll swing back around to address them.

**Comment by nimbinatus** [comment]
Per discussion with @araiford, I'll be opening up a second PR as an alternate mid-term solution to this issue.

**Comment by nimbinatus** [comment]
Closed in favor of #342

**Pull request closed without merging**
