### PR TITLE
Raxio update

### PR DESCRIPTION
**Pull request by nimbinatus**
To test locally:
```console
$ cd <local-repo-root>
$ git fetch <remote-name> pull/<pr-number>/head:PR-<pr-number>
$ git checkout PR-<pr-number>
$ bundle install
$ bundle exec jekyll serve --config _dev-config.yml 
```

Example based on my machine and assuming this is PR 275:
```console
$ cd ~/helix/design-system/
$ git fetch upstream pull/275/head:PR-275
$ git checkout PR-275
$ bundle install
$ bundle exec jekyll serve --config _dev-config.yml 
```

### CODE REVIEW

**Comment by araiford** [comment]
@nimbinatus @technabors 

It might be good to make it so the visual indicator on the status page matches the visual indicators throughout the documentation.  Either way we accomplish that is fine -- making the status page indicators look like the ones in the docs, or vice-versa.  

I lean a little towards the visual style of the pills in the docs because they are a little less ominous.  Any preferences?

**Comment by nimbinatus** [comment]
No preference here; either one would be easy to accomplish.

**Comment by araiford** [comment]
@nimbinatus 

ok, let's go with applying the pills to the status page.

**Comment by araiford** [comment]
Legend changes:

Remove the "Unavailable" row
Remove the Icon column, and replace the text in the Status column to the appropriate pill

**Comment by nimbinatus** [comment]
@araiford updates complete

**Comment by araiford** [comment]
👍   merging

**Pull request merged**
