### PR TITLE
Code option 2

### PR DESCRIPTION
**Pull request by nimbinatus**

### CODE REVIEW

**Comment by nimbinatus** [comment]
@araiford and @technabors, it works! Check this out:
screen shot 2017-11-17 at 8 50 52 am

I need to set up the breadcrumbs to pull from the page in component_design, but otherwise, it's working :)

**Comment by nimbinatus** [comment]
And there's the highlighting for the nav and the fix for the breadcrumbs :) See https://github.com/rackerlabs/design-system/pull/342/commits/5537a5728dacdf6ec2ea6e8dde35540058faa100

**Comment by araiford** [comment]
@nimbinatus -- is there any way we can process the html so that the code examples come across with syntax highlighting, etc?  I know that's a lot to ask...

**Comment by nimbinatus** [comment]
Hmm... let me see what I can do, @araiford. I bet I can get it to work.

**Pull request merged**
